services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: animal
      POSTGRES_USER: animaluser
      POSTGRES_PASSWORD: animalpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - animal-network

volumes:
  postgres_data:

networks:
  animal-network: