spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # test
  #  profiles:
  #    active: local
springdoc:
  swagger-ui:
      path: /swagger-ui.html

jwt:
  secret: ajvnkjafnvofdnvasvnasvnlasvnlvnafslvnlanvlkfasvnlkafvnlkfvniavnsvasvnaslvnaslvkansdlnaslasdklmasdlk
  expiration: 3600000 # 1 hour
  refresh:
    expiration: 604800000 # 7 days